### ISSUE TITLE
Only work with console App

### ISSUE THREAD

**Issue by wiserltz** [mrchrisok/OandaV20.2#2]
Hi, 
I test the dll that is Great, but when I create a simple winform or wpf project the dll simple said: bad news the stream not working.
I think something is not compatible with winform or wpf references, but don't know how....

Thanks
LTZ

**Comment by mrchrisok** [comment]
Hi LTZ,

Is the message "Bad news!. Transactions stream is not functioning."?

If so, that message is only found in the example console app that demonstrates usage.
It does not originate from the V20 middleware code.

Your issue is likely due to the specifics of your WinForm/Wpf implementation.
For further analysis, please share the faulty code.

Chris

**Comment by wiserltz** [comment]
The problem is the function:


namespace OkonkwoOandaV20.TradeLibrary.REST
{
   public partial class Rest20
   {
      /// <summary>
      /// Get a stream of Transactions for an Account starting from when the request is made
      /// </summary>
      /// <param name="accountID">the account ID you want to stream on</param>
      /// <returns>the WebResponse object that can be used to retrieve the events as they stream</returns>
      **public static async Task<WebResponse> GetTransactionsStream(string accountID)**
      {
         string uri = ServerUri(EServer.TransactionsStream) + "accounts/" + accountID + "/transactions/stream";

         HttpWebRequest request = WebRequest.CreateHttp(uri);
         request.Method = "GET";
         request.Headers[HttpRequestHeader.Authorization] = "Bearer " + AccessToken;

         try
         {
            WebResponse response = await request.GetResponseAsync();
            return response;
         }
         catch (WebException ex)
         {
            var response = (HttpWebResponse)ex.Response;
            var stream = new StreamReader(response.GetResponseStream());
            var result = stream.ReadToEnd();
            throw new Exception(result);
         }
      }
   }

Dead locked at: WebResponse response = await request.GetResponseAsync();
never return and not any exceptions

LTZ

**Comment by mrchrisok** [comment]
LTZ,

Download and run the example console app.
Compare your implementation to the example to ensure that calls from you app are made similarly.

The pricing stream and transactions stream are created in identical fashion, so if your app successfully starts the pricing stream, then any difficulty with the transaction stream may be due to parameters, configuration or other factors specific to your app and runtime environment.

Set breakpoints for the GetTransactionsStream call, then do the following:

Verify that the uri is correct.
Verify that the accountID passed in is correct.
Verify that the AccessToken passed in is correct.

Use Fiddler to examine the https traffic to verify that the request is properly formed review any response.

If the failures are occuring in the **Practice** environment, run your application using a **Trade** account with minimal funding to determine if transactions are currently available in **Practice**.

Chris

**Comment by victorarshon** [comment]
Thank you for your library.
However, I have the same problem as LTZ had. 
When I start your sample in the console application, I have the access to my OANDA account and the transactions works. But if I create a simple WinForm application, the success variable in the StartTransactionsStream() subroutine is always returned false. It means: "Bad news!. Transactions stream is not functioning."
Please see the fragment of my code attached.
Could you give a sample of code for WinForm application?
Thanks
Victor
 private void btnTransaction_Click(object sender, EventArgs e)
        {
            MainTransaction();
        }

         void MainTransaction()  
        {
            WriteNewLine("Hello trader! Welcome to OkonkwoOandaV20.2");

            SetApiCredentials();

            StartTransactionsStream();

            PutOnATrade().Wait();

            StopTransactionsStream();

            Console.ReadKey();
        }
