### ISSUE TITLE
Pending Orders Request Question

### ISSUE THREAD

**Issue by weidner** [mrchrisok/OandaV20.2#8]
Hi,

When I make a call something like the following:

                var pendingOrderCall = Rest20.GetPendingOrdersAsync(AccountID);
                pendingOrderCall.Wait();
                var pendingOrderList = pendingOrderCall.Result;

When I look at the pendingOrderCall.Result object, I see what looks like a List<PendingEntryOrder> object that has fields like instrument, price, state, etc.

But when I assign pendingOrderCall.Result to pendingOrderList, I get a List<IOrder> which has no instrument, price, state, etc.

Is there a way to get that info?

Thank you!
Dave Weidner

**Comment by mrchrisok** [comment]
Hi Dave,

Because the pending orders can be of varied types, GetPendingOrders returns them as a list of IOrder objects.
Depending on which order type you are expecting or are looking for, you can discover that with logic like this:

var limitOrders = orderList.Where(x => x.type == OrderType.Limit).ToList(x => (LimitOrder)x);

Hope this helps.
Chris
